source 'https://rubygems.org'

# Fixing gem versions supported by traveling-ruby
gem 'json', '1.8.3'
gem 'nokogiri', '1.6.6.2'
gem 'blockenspiel', '0.4.5'
gem 'eventmachine', '1.0.8'
gem 'redcarpet', '3.3.3'
gem 'thin', '1.6.4'
gem 'sqlite3', '1.3.11'
gem 'mysql2', '0.4.1'
gem 'pg', '0.18.3'
gem "pact_broker", "1.9.0"

